seed: 42

paths:
  radiomics_parquet_dir: /root/workspace/datasets/hest_data/hestbench_h5/all_radiomics_normed_parquets
  output_dir: /root/workspace/datasets/hest_data/hestbench_h5/all_radiomics_normed_tabular
  log_dir: /root/workspace/datasets/hest_data/hestbench_h5/all_radiomics_normed_tabular/logs

dataset:
  meta_columns:
    - sample_id
    - patch_idx
    - patch_id
    - barcode
    - status
    - color_path
    - gray_path
    - mask_path
    - x
    - y 
  
  exclude_prefixes:
    - diagnostics_

  radiomics_valid_prefixes:
    - original_
    # - squareroot_
    # - logarithm_
    # - wavelet-
    # - exponential_
    # - square_
    # - log-sigma-

  sample_label_map:
    # IDC 
    NCBI783: 0
    NCBI785: 0
    TENX95: 0
    TENX99: 0

    # CCRCC
    INT1: 1
    INT2: 1
    INT3: 1
    INT4: 1
    INT5: 1
    INT6: 1
    INT7: 1
    INT8: 1
    INT9: 1
    INT10: 1
    INT11: 1
    INT12: 1
    INT13: 1
    INT14: 1
    INT15: 1
    INT16: 1
    INT17: 1
    INT18: 1
    INT19: 1
    INT20: 1
    INT21: 1
    INT22: 1
    INT23: 1
    INT24: 1

    # COAD
    TENX111: 2
    TENX147: 2
    TENX148: 2
    TENX149: 2

    # HCC
    NCBI642: 3
    NCBI643: 3

    # LUNG
    TENX118: 4
    TENX141: 4

    # LYMPH_IDC
    NCBI681: 5
    NCBI682: 5
    NCBI683: 5
    NCBI684: 5

    # PAAD
    TENX116: 6
    TENX126: 6
    TENX140: 6

    # PRAD
    MEND139: 7
    MEND140: 7
    MEND141: 7
    MEND142: 7
    MEND143: 7
    MEND144: 7
    MEND145: 7
    MEND146: 7
    MEND147: 7
    MEND148: 7
    MEND149: 7
    MEND150: 7
    MEND151: 7
    MEND152: 7
    MEND153: 7
    MEND154: 7
    MEND155: 7
    MEND156: 7
    MEND157: 7
    MEND158: 7
    MEND159: 7
    MEND160: 7
    MEND161: 7
    MEND162: 7

    # READ
    ZEN36: 8
    ZEN40: 8
    ZEN48: 8
    ZEN49: 8 

    # SKCM 
    TENX115: 9
    TENX117: 9 

  lowercase_columns: true
  check_numeric: true
  check_nan: true

runtime:
  test_load_single_data: true
  encode_cat: false

