seed: 42

paths:
  radiomics_parquet_dir: /root/workspace/datasets/hest_data/extended_IDC_h5/features/TENX99_features/radiomics_normed_parquets
  output_dir: /root/workspace/datasets/hest_data/extended_IDC_h5/features/TENX99_features/radiomics_normed_tabular
  log_dir: /root/workspace/datasets/hest_data/extended_IDC_h5/features/TENX99_features/logs 

dataset:
  meta_columns:
    - sample_id
    - patch_idx
    - patch_id
    - barcode
    - status
    - color_path
    - gray_path
    - mask_path
    - x
    - y 

  exclude_prefixes:
    - diagnostics_

  radiomics_valid_prefixes:
    - original_
    # - squareroot_
    # - logarithm_
    # - wavelet-
    # - exponential_
    # - square_
    # - log-sigma-

  sample_label_map:
    # IDC 
    TENX99: 0

  lowercase_columns: true
  check_numeric: true
  check_nan: true

runtime:
  test_load_single_data: true
  encode_cat: false

