# Name of the files used for checkpointing
TRAINING_ARGS_NAME = "training_args.json"
TRAINER_STATE_NAME = "trainer_state.json"
OPTIMIZER_NAME = "optimizer.pt"
SCHEDULER_NAME = "scheduler.pt"
WEIGHTS_NAME = "pytorch_model.bin"
TOKENIZER_DIR = 'tokenizer'
EXTRACTOR_STATE_DIR = 'extractor'
EXTRACTOR_STATE_NAME = 'extractor.json'
INPUT_ENCODER_NAME = 'input_encoder.bin'
TRANSTAB_PARAMS_NAME = 'transtab_params.json'


# Building Commons 
DEFAULT_CATEGORICAL_COLUMNS = None
DEFAULT_NUMERICAL_COLUMNS = None
DEFAULT_BINARY_COLUMNS = None


# Building Feature Extractor
IGNORE_DUPLICATE_COLS = False
DISABLE_TOKENIZER_PARALLEL = False


# Building Classifier 
CLASSIFIER_FEATURE_EXTRACTOR = None
CLASSIFIER_NUM_CLASS = 2
CLASSIFIER_HIDDEN_DIM = 128
CLASSIFIER_NUM_LAYER = 2
CLASSIFIER_NUM_ATTENTION_HEAD = 8
CLASSIFIER_HIDDEN_DROPOUT_PROB = 0
CLASSIFIER_FFN_DIM = 256
CLASSIFIER_ACTIVATION = 'relu'
CLASSIFIER_DEVICE = 'cuda:0'


# Building Radiomics Learner 
RADTRANSTAB_FEATURE_EXTRACTOR = None
RADTRANSTAB_NUM_CLASS = 2
RADTRANSTAB_HIDDEN_DIM = 128
RADTRANSTAB_NUM_LAYER = 2
RADTRANSTAB_NUM_ATTENTION_HEAD = 8
RADTRANSTAB_HIDDEN_DROPOUT_PROB = 0
RADTRANSTAB_FFN_DIM = 256
RADTRANSTAB_ACTIVATION = 'relu'
RADTRANSTAB_DEVICE = 'cuda:0'

RADTRANSTAB_PROJECTION_DIM = 128
RADTRANSTAB_NUM_SUB_COLS = [72, 54, 36, 18, 9, 3, 1]
RADTRANSTAB_GPE_DROP_RATE = 0.1
